Fixed problem with DO_BYTE_IS_OUTPUT (#89)
* Fixed missing vars and added more printing

* Fixed problem with DO_BYTE_IS_OUTPUT


def get_DO_BYTE(uut, idx):
    if uut.DO_BYTE_IS_OUTPUT:
        if uut.DO_BYTE_IS_OUTPUT[idx]:
Member
@petermilne petermilne Pending
This is a nice idea but it's not going to work.

stuff = []
stiff.append('A')
stuff.append('B')
if stuff[4]:
... print("Stuff 4 exists")
IndexError: list index out of range

instead:

try:
... mything=stuff[4]
... except IndexError:
... mything=stuff[0]

---------

Co-authored-by: Peter Milne <petermilne@users.noreply.github.com>